# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Crypto-List' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Crypto-List
  pod 'Alamofire'
  pod 'SDWebImageSwiftUI'
  pod 'SDWebImageSVGCoder'

  target 'Crypto-ListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Crypto-ListUITests' do
    # Pods for testing
  end

end
